CodingEvents/Controllers/EventCategoryController.cs
using CodingEvents.Data;
using CodingEvents.Models;
using CodingEvents.ViewModles;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CodingEvents.Controllers
{

    
    public class EventCategoryController : Controller
    {

        private EventDbContext _context;

        public EventCategoryController(EventDbContext dbContext)
        {
            _context = dbContext; 
        }


        public IActionResult Index()
        {
            List<EventCategory> eventCategories = _context.Categories.ToList();
            return View(eventCategories);
        }


        public IActionResult Create()
        {
            AddEventCategoryViewModel addEventCategoryViewModel = new AddEventCategoryViewModel();
            return View(addEventCategoryViewModel);
        }

        [HttpPost]
        //[Route("/create")]
        public IActionResult /*ProcessCreateEventCategoryForm*/Create(AddEventCategoryViewModel addEventCategoryViewModel)
        {
            if (ModelState.IsValid)
            {
                EventCategory newEventCategory = new EventCategory
                {
                    Name = addEventCategoryViewModel.Name
                };
                _context.Categories.Add(newEventCategory);
                _context.SaveChanges();
                return Redirect("Index");
            }

            return View();


        }
    }
}

CodingEvents/Controllers/EventsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CodingEvents.Models;
using CodingEvents.Data;
using CodingEvents.ViewModles;
using Microsoft.EntityFrameworkCore;

namespace CodingEvents.Controllers
{
    
    public class EventsController : Controller
    {
        //private static List<string> Events = new List<string>();

        /*private static List<Event> Events = new List<Event>();*/


        private EventDbContext context;
        public EventsController(EventDbContext dbContext)
        {
            context = dbContext;
        }

        

        [HttpGet]
        public IActionResult Index()
        {


            //ViewBag.events = EventData.GetAll();
            /*List<Event> events = new List<Event>(EventData.GetAll());*/
            List<Event> events = context.Events
                .Include(e => e.Category) // include foreign key
                .ToList();

            return View(events);
        }

        [HttpGet] 
        // /events/add
        public IActionResult Add()
        {
            List<EventCategory> categories = context.Categories.ToList();
            AddEventViewModel addEventViewModel = new AddEventViewModel(categories);
            return View(addEventViewModel);
        }

        [HttpPost]
        //[Route("/events/add")]
        public IActionResult Add(AddEventViewModel addEventViewModel)
        {
            if (ModelState.IsValid)
            {
                EventCategory theCategory = context.Categories.Find(addEventViewModel.CategoryId);
                Event newEvent = new Event
                {
                    Name = addEventViewModel.Name,
                    Description = addEventViewModel.Description,
                    ContactEmail = addEventViewModel.ContactEmail,
                    Location = addEventViewModel.Location,
                    Attendees = addEventViewModel.Attendees,
                    RegistrationRequired = addEventViewModel.RegistrationRequired,
                    //Type = addEventViewModel.Type
                    Category = theCategory

                   
                     };

                //EventData.Add(newEvent);
                context.Events.Add(newEvent);
                context.SaveChanges();
                return Redirect("/events");
            }

            return View(addEventViewModel);
            
        }

        public IActionResult Delete()
        {
            //ViewBag.events = EventData.GetAll();
            ViewBag.events = context.Events.ToList();
            return View();
        }

        [HttpPost]
        public IActionResult Delete(int[] eventIds)
        {
            foreach(int i in eventIds)
            {
                //EventData.Remove(i);
                Event theEvent = context.Events.Find(i);
                context.Events.Remove(theEvent);
            }
            context.SaveChanges();
            return Redirect("/Events");
        }

        [Route("/Events/Edit/{eventId?}")]
        public IActionResult Edit(int eventId, string name)
        {
            //ViewBag.eventToBeEdited = EventData.GetById(eventId);
            ViewBag.eventToBeEdited = context.Events.Find(eventId);
            ViewBag.EditEvent = $"Edit Event {name} (id={eventId})";
            return View();
        }

        [HttpPost]
        [Route("/Events/Edit/{eventId?}")]
        public IActionResult SubmitEditEventForm(int eventId, string name, string description, string contactEmail, string location, int attendees)
        {
            /*EventData.Events[eventId].Name = name;
            EventData.Events[eventId].Description = description;*/

            context.Events.Where(x => x.Id == eventId).ToList().ForEach(x => x.Name = name);
            context.Events.Where(x => x.Id == eventId).ToList().ForEach(x => x.Description = description);
            context.Events.Where(x => x.Id == eventId).ToList().ForEach(x => x.ContactEmail = contactEmail);
            context.Events.Where(x => x.Id == eventId).ToList().ForEach(x => x.Location = location);
            context.Events.Where(x => x.Id == eventId).ToList().ForEach(x => x.Attendees = attendees);
            context.SaveChanges();

            return Redirect("/Events");
        }


        public IActionResult Detail(int id)
        {
            Event theEvent = context.Events
                .Include(e => e.Category)
                .Single(e => e.Id == id);

            List<EventTag> eventTags = context.EventTags
                .Where(et => et.EventId == id)
                .Include(et => et.Tag)
                .ToList();

            EventDetailViewModel viewModel = new EventDetailViewModel(theEvent, eventTags);
            return View(viewModel);
        }
    }

}

CodingEvents/Controllers/TagController.cs
using CodingEvents.Data;
using CodingEvents.Models;
using CodingEvents.ViewModles;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CodingEvents.Controllers
{
    public class TagController : Controller
    {
        private EventDbContext context;

        public TagController(EventDbContext dbContext)
        {
            context = dbContext;
        }
        public IActionResult Index()
        {
            List<Tag> tags = context.Tags.ToList();

            return View(tags);
        }

        public IActionResult Add()
        {
            Tag tag = new Tag();
            return View(tag);
        }

        [HttpPost]
        public IActionResult Add(Tag tag)
        {
            if (ModelState.IsValid)
            {
                context.Tags.Add(tag);
                context.SaveChanges();
                return Redirect("/Tag/");
            }

            return View("Add", tag);
        }


        public IActionResult AddEvent(int id)
        {
            Event theEvent = context.Events.Find(id);
            List<Tag> possibleTags = context.Tags.ToList();

            AddEventTagViewModel viewModel = new AddEventTagViewModel(theEvent, possibleTags);

            return View(viewModel);
        }


        [HttpPost]
        public IActionResult AddEvent(AddEventTagViewModel viewModel)
        {
            if(ModelState.IsValid)
            {
                int eventId = viewModel.EventId;
                int tagId = viewModel.TagId;

                List<EventTag> existingItems = context.EventTags
                    .Where(et => et.EventId == eventId)
                    .Where(et => et.TagId == tagId)
                    .ToList();

                if(existingItems.Count == 0)
                {

                    EventTag eventTag = new EventTag
                         {
                             EventId = eventId,
                             TagId = tagId
                        };

                    context.EventTags.Add(eventTag);
                    context.SaveChanges();

                }

                

                return Redirect("/Events/Detail/" + eventId);

            }

            return View(viewModel);
        }



        public IActionResult Detail(int id)
        {
            List<EventTag> eventTags = context.EventTags
                .Where(et => et.TagId == id)
                .Include(et => et.Event)//include method -> egar load 
                .Include(et => et.Tag)
                .ToList();

            return View(eventTags);
        }

    }
}

CodingEvents/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CodingEvents</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CodingEvents</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            @*<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>*@
                            <a class="nav-link text-dark" asp-area="" asp-controller="Events" asp-action="Index">Index</a>
                        </li>
                        <li class="nav-item">
                            @*<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>*@
                            <a class="nav-link text-dark" asp-area="" asp-controller="Events" asp-action="Add">Add</a>
                        </li>
                        <li class="nav-item">

                            <a class="nav-link text-dark" asp-area="" asp-controller="Events" asp-action="Delete">Delete</a>
                        </li>
                        <li class="nav-item">

                            <a class="nav-link text-dark" asp-area="" asp-controller="EventCategory" asp-action="Create">Create Event Category</a>
                        </li>

                        <li class="nav-item">

                            <a class="nav-link text-dark" asp-area="" asp-controller="EventCategory" asp-action="Index">Event Category Index</a>
                        </li>

                        <li class="nav-item">

                            <a class="nav-link text-dark" asp-area="" asp-controller="Tag" asp-action="Index">All Tags</a>
                        </li>

                        <li class="nav-item">

                            <a class="nav-link text-dark" asp-area="" asp-controller="Tag" asp-action="Add">Add Tag</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - CodingEvents - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>